repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.0
  hooks:
  - id: ruff
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.0
  hooks:
  - id: mypy
    exclude: (\.venv|venv|\.git|\.eggs|\.mypy_cache|build|dist)
    files: ^(llm|modules)/
    additional_dependencies:
    - types-click
    - types-PyYAML
    - ollama
